name: internal-refs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  no-internal-refs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 20
      - name: Check for internal references
        run: node .github/scripts/no-internal-refs.mjs
